# Generated by Django 4.1.7 on 2023-06-15 15:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import posts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users_pet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('media', models.ImageField(upload_to=posts.models.user_directory_path)),
                ('post_likes', models.ManyToManyField(related_name='liked_posts', to='users_pet.profile')),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_pet.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField(null=True)),
                ('comment_likes', models.ManyToManyField(related_name='liked_comments', to='users_pet.profile')),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_pet.profile')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
            ],
        ),
    ]
