# Generated by Django 4.1.7 on 2023-06-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscribed',
            field=models.ManyToManyField(blank=True, to='users.profile'),
        ),
    ]
