# Generated by Django 4.1.7 on 2023-06-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_subscribed'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='/static/default.jpg', upload_to='static/profile_pics'),
        ),
    ]
